#ifndef LIGHT_GUN_DRIVER_TEST_RUMBLE_TEST_H
#define LIGHT_GUN_DRIVER_TEST_RUMBLE_TEST_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * 振动马达测试默认使用 PWM 输出。
 *
 * 默认值按当前测试硬件约定：
 * - channel: 1
 * - pin: GPIO1
 * - pin mode: 42
 *
 * 这里故意把默认值放在 42，不再放 41。
 * 原因是当前芯片头文件注释里，41 更像 PWM0_COMP，
 * 而 42 的注释更接近“PWM1 正向输出”。
 * 如果你的板级原理图确认不是这样，再按硬件实际修改。
 */
#ifndef RUMBLE_TEST_PWM_CHANNEL
#ifdef CONFIG_LIGHT_GUN_RUMBLE_PWM_CHANNEL
#define RUMBLE_TEST_PWM_CHANNEL CONFIG_LIGHT_GUN_RUMBLE_PWM_CHANNEL
#else
#define RUMBLE_TEST_PWM_CHANNEL 1
#endif
#endif

#ifndef RUMBLE_TEST_PWM_GROUP_ID
#ifdef CONFIG_LIGHT_GUN_RUMBLE_PWM_GROUP_ID
#define RUMBLE_TEST_PWM_GROUP_ID CONFIG_LIGHT_GUN_RUMBLE_PWM_GROUP_ID
#else
#define RUMBLE_TEST_PWM_GROUP_ID 0
#endif
#endif

#ifndef RUMBLE_TEST_PWM_PIN
#ifdef CONFIG_LIGHT_GUN_RUMBLE_PWM_PIN
#define RUMBLE_TEST_PWM_PIN CONFIG_LIGHT_GUN_RUMBLE_PWM_PIN
#else
#define RUMBLE_TEST_PWM_PIN 1
#endif
#endif

#ifndef RUMBLE_TEST_PWM_PIN_MODE
#ifdef CONFIG_LIGHT_GUN_RUMBLE_PWM_PIN_MODE
#define RUMBLE_TEST_PWM_PIN_MODE CONFIG_LIGHT_GUN_RUMBLE_PWM_PIN_MODE
#else
#define RUMBLE_TEST_PWM_PIN_MODE 42
#endif
#endif

/*
 * 闭环测试用例选择。
 *
 * 每个用例验证的点如下：
 *
 * 1. CONTINUOUS_DIAG
 *    诊断模式：
 *    持续输出固定 PWM，不走脉冲状态机。
 *    这个模式专门用来先验证“GPIO1/PWM1/pinmux/示波器接法”。
 *
 * 1. SINGLE_PULSE_ONCE
 *    验证最基础的单次振动脉冲：
 *    PWM 是否能从 0% 切到目标占空比，再回到 0%。
 *
 * 2. PERIODIC_PULSE
 *    验证周期性短振动：
 *    检查软件定时器稳定性，以及每个周期是否只触发一次振动。
 *
 * 3. BOUNDED_AUTOFIRE
 *    验证有限多脉冲连续振动：
 *    一轮里连续震动几次，再休息。
 *
 * 4. DUTY_SWEEP
 *    验证占空比强度映射：
 *    让振动强度从低到高分阶段变化，便于观察“力度是否随占空比变化”。
 *
 * 5. SAFETY_CLAMP
 *    验证安全钳位：
 *    故意请求超范围强度和较长动作时间，检查是否被自动裁剪。
 */
#define RUMBLE_TEST_CASE_CONTINUOUS_DIAG        1
#define RUMBLE_TEST_CASE_SINGLE_PULSE_ONCE      2
#define RUMBLE_TEST_CASE_PERIODIC_PULSE         3
#define RUMBLE_TEST_CASE_BOUNDED_AUTOFIRE       4
#define RUMBLE_TEST_CASE_DUTY_SWEEP             5
#define RUMBLE_TEST_CASE_SAFETY_CLAMP           6

#ifndef RUMBLE_TEST_CASE
#if defined(CONFIG_LIGHT_GUN_RUMBLE_CASE_CONTINUOUS_DIAG)
#define RUMBLE_TEST_CASE RUMBLE_TEST_CASE_CONTINUOUS_DIAG
#elif defined(CONFIG_LIGHT_GUN_RUMBLE_CASE_SINGLE_PULSE_ONCE)
#define RUMBLE_TEST_CASE RUMBLE_TEST_CASE_SINGLE_PULSE_ONCE
#elif defined(CONFIG_LIGHT_GUN_RUMBLE_CASE_PERIODIC_PULSE)
#define RUMBLE_TEST_CASE RUMBLE_TEST_CASE_PERIODIC_PULSE
#elif defined(CONFIG_LIGHT_GUN_RUMBLE_CASE_BOUNDED_AUTOFIRE)
#define RUMBLE_TEST_CASE RUMBLE_TEST_CASE_BOUNDED_AUTOFIRE
#elif defined(CONFIG_LIGHT_GUN_RUMBLE_CASE_DUTY_SWEEP)
#define RUMBLE_TEST_CASE RUMBLE_TEST_CASE_DUTY_SWEEP
#elif defined(CONFIG_LIGHT_GUN_RUMBLE_CASE_SAFETY_CLAMP)
#define RUMBLE_TEST_CASE RUMBLE_TEST_CASE_SAFETY_CLAMP
#else
#define RUMBLE_TEST_CASE RUMBLE_TEST_CASE_CONTINUOUS_DIAG
#endif
#endif

/* 安全优先默认参数。 */
#ifndef RUMBLE_TEST_START_DELAY_MS
#ifdef CONFIG_LIGHT_GUN_RUMBLE_START_DELAY_MS
#define RUMBLE_TEST_START_DELAY_MS CONFIG_LIGHT_GUN_RUMBLE_START_DELAY_MS
#else
#define RUMBLE_TEST_START_DELAY_MS 1500U
#endif
#endif

#ifndef RUMBLE_TEST_LEVEL_PERCENT
#ifdef CONFIG_LIGHT_GUN_RUMBLE_LEVEL_PERCENT
#define RUMBLE_TEST_LEVEL_PERCENT CONFIG_LIGHT_GUN_RUMBLE_LEVEL_PERCENT
#else
#define RUMBLE_TEST_LEVEL_PERCENT 70U
#endif
#endif

#ifndef RUMBLE_TEST_ACTIVE_MS
#ifdef CONFIG_LIGHT_GUN_RUMBLE_ACTIVE_MS
#define RUMBLE_TEST_ACTIVE_MS CONFIG_LIGHT_GUN_RUMBLE_ACTIVE_MS
#else
#define RUMBLE_TEST_ACTIVE_MS 120U
#endif
#endif

#ifndef RUMBLE_TEST_GAP_MS
#ifdef CONFIG_LIGHT_GUN_RUMBLE_GAP_MS
#define RUMBLE_TEST_GAP_MS CONFIG_LIGHT_GUN_RUMBLE_GAP_MS
#else
#define RUMBLE_TEST_GAP_MS 180U
#endif
#endif

#ifndef RUMBLE_TEST_PERIOD_MS
#ifdef CONFIG_LIGHT_GUN_RUMBLE_PERIOD_MS
#define RUMBLE_TEST_PERIOD_MS CONFIG_LIGHT_GUN_RUMBLE_PERIOD_MS
#else
#define RUMBLE_TEST_PERIOD_MS 1000U
#endif
#endif

#ifndef RUMBLE_TEST_CYCLE_REST_MS
#ifdef CONFIG_LIGHT_GUN_RUMBLE_CYCLE_REST_MS
#define RUMBLE_TEST_CYCLE_REST_MS CONFIG_LIGHT_GUN_RUMBLE_CYCLE_REST_MS
#else
#define RUMBLE_TEST_CYCLE_REST_MS 1500U
#endif
#endif

#ifndef RUMBLE_TEST_AUTOFIRE_PULSES
#ifdef CONFIG_LIGHT_GUN_RUMBLE_AUTOFIRE_PULSES
#define RUMBLE_TEST_AUTOFIRE_PULSES CONFIG_LIGHT_GUN_RUMBLE_AUTOFIRE_PULSES
#else
#define RUMBLE_TEST_AUTOFIRE_PULSES 5U
#endif
#endif

#ifndef RUMBLE_TEST_SWEEP_STEPS
#ifdef CONFIG_LIGHT_GUN_RUMBLE_SWEEP_STEPS
#define RUMBLE_TEST_SWEEP_STEPS CONFIG_LIGHT_GUN_RUMBLE_SWEEP_STEPS
#else
#define RUMBLE_TEST_SWEEP_STEPS 4U
#endif
#endif

/*
 * 安全钳位：
 * - 强度最大 100%
 * - 单次持续时间不超过该值
 */
#ifndef RUMBLE_TEST_MAX_LEVEL_PERCENT
#ifdef CONFIG_LIGHT_GUN_RUMBLE_MAX_LEVEL_PERCENT
#define RUMBLE_TEST_MAX_LEVEL_PERCENT CONFIG_LIGHT_GUN_RUMBLE_MAX_LEVEL_PERCENT
#else
#define RUMBLE_TEST_MAX_LEVEL_PERCENT 100U
#endif
#endif

#ifndef RUMBLE_TEST_MAX_ACTIVE_MS
#ifdef CONFIG_LIGHT_GUN_RUMBLE_MAX_ACTIVE_MS
#define RUMBLE_TEST_MAX_ACTIVE_MS CONFIG_LIGHT_GUN_RUMBLE_MAX_ACTIVE_MS
#else
#define RUMBLE_TEST_MAX_ACTIVE_MS 300U
#endif
#endif

void rumble_test_overlay_entry(void);

#ifdef __cplusplus
}
#endif

#endif
