#ifndef LIGHT_GUN_DRIVER_TEST_USB_SIM_TEST_H
#define LIGHT_GUN_DRIVER_TEST_USB_SIM_TEST_H

#ifdef __cplusplus
extern "C" {
#endif

#ifndef USB_SIM_TEST_START_DELAY_MS
#ifdef CONFIG_LIGHT_GUN_USB_START_DELAY_MS
#define USB_SIM_TEST_START_DELAY_MS CONFIG_LIGHT_GUN_USB_START_DELAY_MS
#else
#define USB_SIM_TEST_START_DELAY_MS 1500U
#endif
#endif

#ifndef USB_SIM_TEST_POLL_MS
#ifdef CONFIG_LIGHT_GUN_USB_POLL_MS
#define USB_SIM_TEST_POLL_MS CONFIG_LIGHT_GUN_USB_POLL_MS
#else
#define USB_SIM_TEST_POLL_MS 10U
#endif
#endif

#ifndef USB_SIM_TEST_DEBOUNCE_MS
#ifdef CONFIG_LIGHT_GUN_USB_DEBOUNCE_MS
#define USB_SIM_TEST_DEBOUNCE_MS CONFIG_LIGHT_GUN_USB_DEBOUNCE_MS
#else
#define USB_SIM_TEST_DEBOUNCE_MS 30U
#endif
#endif

#ifndef USB_SIM_TEST_SCRIPT_STEP_MS
#ifdef CONFIG_LIGHT_GUN_USB_SCRIPT_STEP_MS
#define USB_SIM_TEST_SCRIPT_STEP_MS CONFIG_LIGHT_GUN_USB_SCRIPT_STEP_MS
#else
#define USB_SIM_TEST_SCRIPT_STEP_MS 250U
#endif
#endif

#ifndef USB_SIM_TEST_TRIGGER_TOGGLE_MS
#ifdef CONFIG_LIGHT_GUN_USB_TRIGGER_MODE_TOGGLE_MS
#define USB_SIM_TEST_TRIGGER_TOGGLE_MS CONFIG_LIGHT_GUN_USB_TRIGGER_MODE_TOGGLE_MS
#else
#define USB_SIM_TEST_TRIGGER_TOGGLE_MS 4000U
#endif
#endif

#if defined(CONFIG_LIGHT_GUN_USB_SIM_FAKE_IR)
#define USB_SIM_TEST_ENABLE_FAKE_IR 1
#else
#define USB_SIM_TEST_ENABLE_FAKE_IR 0
#endif

#if defined(CONFIG_LIGHT_GUN_USB_SIM_FAKE_LED)
#define USB_SIM_TEST_ENABLE_FAKE_LED 1
#else
#define USB_SIM_TEST_ENABLE_FAKE_LED 0
#endif

#if defined(CONFIG_LIGHT_GUN_USB_SIM_SCRIPT_MOUSE_MOVE)
#define USB_SIM_TEST_ENABLE_SCRIPT_MOUSE_MOVE 1
#else
#define USB_SIM_TEST_ENABLE_SCRIPT_MOUSE_MOVE 0
#endif

#if defined(CONFIG_LIGHT_GUN_USB_SIM_SCRIPT_MOUSE_CLICK)
#define USB_SIM_TEST_ENABLE_SCRIPT_MOUSE_CLICK 1
#else
#define USB_SIM_TEST_ENABLE_SCRIPT_MOUSE_CLICK 0
#endif

#if defined(CONFIG_LIGHT_GUN_USB_SIM_SCRIPT_KEYBOARD)
#define USB_SIM_TEST_ENABLE_SCRIPT_KEYBOARD 1
#else
#define USB_SIM_TEST_ENABLE_SCRIPT_KEYBOARD 0
#endif

#if defined(CONFIG_LIGHT_GUN_USB_SIM_GPIO_PASSTHROUGH)
#define USB_SIM_TEST_ENABLE_GPIO_PASSTHROUGH 1
#else
#define USB_SIM_TEST_ENABLE_GPIO_PASSTHROUGH 0
#endif

#if defined(CONFIG_LIGHT_GUN_USB_SIM_TRIGGER_REF)
#define USB_SIM_TEST_ENABLE_TRIGGER_REF 1
#else
#define USB_SIM_TEST_ENABLE_TRIGGER_REF 0
#endif

#if defined(CONFIG_LIGHT_GUN_USB_SIM_USE_IR_LIVE_MOUSE)
#define USB_SIM_TEST_ENABLE_IR_LIVE_MOUSE 1
#else
#define USB_SIM_TEST_ENABLE_IR_LIVE_MOUSE 0
#endif

#define USB_SIM_TEST_OFFSCREEN_DISABLE         0
#define USB_SIM_TEST_OFFSCREEN_RIGHT_CLICK     1

#ifndef USB_SIM_TEST_OFFSCREEN_MODE
#if defined(CONFIG_LIGHT_GUN_USB_OFFSCREEN_MODE_DISABLE)
#define USB_SIM_TEST_OFFSCREEN_MODE USB_SIM_TEST_OFFSCREEN_DISABLE
#elif defined(CONFIG_LIGHT_GUN_USB_OFFSCREEN_MODE_RIGHT_CLICK)
#define USB_SIM_TEST_OFFSCREEN_MODE USB_SIM_TEST_OFFSCREEN_RIGHT_CLICK
#else
#define USB_SIM_TEST_OFFSCREEN_MODE USB_SIM_TEST_OFFSCREEN_RIGHT_CLICK
#endif
#endif

#ifndef USB_SIM_TEST_BTN_A_PIN
#ifdef CONFIG_LIGHT_GUN_USB_BTN_A_PIN
#define USB_SIM_TEST_BTN_A_PIN CONFIG_LIGHT_GUN_USB_BTN_A_PIN
#else
#define USB_SIM_TEST_BTN_A_PIN 23
#endif
#endif

#ifndef USB_SIM_TEST_BTN_B_PIN
#ifdef CONFIG_LIGHT_GUN_USB_BTN_B_PIN
#define USB_SIM_TEST_BTN_B_PIN CONFIG_LIGHT_GUN_USB_BTN_B_PIN
#else
#define USB_SIM_TEST_BTN_B_PIN 22
#endif
#endif

#ifndef USB_SIM_TEST_BTN_TRIGGER_PIN
#ifdef CONFIG_LIGHT_GUN_USB_BTN_TRIGGER_PIN
#define USB_SIM_TEST_BTN_TRIGGER_PIN CONFIG_LIGHT_GUN_USB_BTN_TRIGGER_PIN
#else
#define USB_SIM_TEST_BTN_TRIGGER_PIN 21
#endif
#endif

#ifndef USB_SIM_TEST_BTN_START_PIN
#ifdef CONFIG_LIGHT_GUN_USB_BTN_START_PIN
#define USB_SIM_TEST_BTN_START_PIN CONFIG_LIGHT_GUN_USB_BTN_START_PIN
#else
#define USB_SIM_TEST_BTN_START_PIN 18
#endif
#endif

#ifndef USB_SIM_TEST_BTN_SELECT_PIN
#ifdef CONFIG_LIGHT_GUN_USB_BTN_SELECT_PIN
#define USB_SIM_TEST_BTN_SELECT_PIN CONFIG_LIGHT_GUN_USB_BTN_SELECT_PIN
#else
#define USB_SIM_TEST_BTN_SELECT_PIN 17
#endif
#endif

#ifndef USB_SIM_TEST_BTN_HOME_PIN
#ifdef CONFIG_LIGHT_GUN_USB_BTN_HOME_PIN
#define USB_SIM_TEST_BTN_HOME_PIN CONFIG_LIGHT_GUN_USB_BTN_HOME_PIN
#else
#define USB_SIM_TEST_BTN_HOME_PIN 16
#endif
#endif

#ifndef USB_SIM_TEST_BTN_GAMEPAD_PIN
#ifdef CONFIG_LIGHT_GUN_USB_BTN_GAMEPAD_PIN
#define USB_SIM_TEST_BTN_GAMEPAD_PIN CONFIG_LIGHT_GUN_USB_BTN_GAMEPAD_PIN
#else
#define USB_SIM_TEST_BTN_GAMEPAD_PIN 255
#endif
#endif

#ifndef USB_SIM_TEST_BTN_UP_PIN
#ifdef CONFIG_LIGHT_GUN_USB_BTN_UP_PIN
#define USB_SIM_TEST_BTN_UP_PIN CONFIG_LIGHT_GUN_USB_BTN_UP_PIN
#else
#define USB_SIM_TEST_BTN_UP_PIN 27
#endif
#endif

#ifndef USB_SIM_TEST_BTN_DOWN_PIN
#ifdef CONFIG_LIGHT_GUN_USB_BTN_DOWN_PIN
#define USB_SIM_TEST_BTN_DOWN_PIN CONFIG_LIGHT_GUN_USB_BTN_DOWN_PIN
#else
#define USB_SIM_TEST_BTN_DOWN_PIN 28
#endif
#endif

#ifndef USB_SIM_TEST_BTN_LEFT_PIN
#ifdef CONFIG_LIGHT_GUN_USB_BTN_LEFT_PIN
#define USB_SIM_TEST_BTN_LEFT_PIN CONFIG_LIGHT_GUN_USB_BTN_LEFT_PIN
#else
#define USB_SIM_TEST_BTN_LEFT_PIN 29
#endif
#endif

#ifndef USB_SIM_TEST_BTN_RIGHT_PIN
#ifdef CONFIG_LIGHT_GUN_USB_BTN_RIGHT_PIN
#define USB_SIM_TEST_BTN_RIGHT_PIN CONFIG_LIGHT_GUN_USB_BTN_RIGHT_PIN
#else
#define USB_SIM_TEST_BTN_RIGHT_PIN 30
#endif
#endif

#ifndef USB_SIM_TEST_BTN_MIDDLE_PIN
#ifdef CONFIG_LIGHT_GUN_USB_BTN_MIDDLE_PIN
#define USB_SIM_TEST_BTN_MIDDLE_PIN CONFIG_LIGHT_GUN_USB_BTN_MIDDLE_PIN
#else
#define USB_SIM_TEST_BTN_MIDDLE_PIN 0
#endif
#endif

void usb_sim_test_overlay_entry(void);

#ifdef __cplusplus
}
#endif

#endif
