#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
workspace_root="$(cd "${script_dir}/../.." && pwd)"
profile_file="${script_dir}/build_profile.conf"
projects_root="${workspace_root}/projects"
patch_root="${workspace_root}/patches/sdk/sdk_root_dir"

list_projects() { find "${projects_root}" -mindepth 1 -maxdepth 1 -type d -printf "%f\n" | sort; }
list_patch_sets() { [[ -d "${patch_root}" ]] && find "${patch_root}" -mindepth 1 -maxdepth 1 -type d -printf "%f\n" | sort || true; }

patch_set_note() {
    local set_name="$1"
    local notes_file="${patch_root}/${set_name}/PATCH_NOTES.txt"
    local patch_count=0
    if [[ -d "${patch_root}/${set_name}" ]]; then
        patch_count=$(find "${patch_root}/${set_name}" -maxdepth 1 -type f -name '*.patch' | wc -l | tr -d ' ')
    fi
    if [[ -f "${notes_file}" ]]; then
        local last_line note_text
        last_line="$(grep -v '^[[:space:]]*$' "${notes_file}" | tail -n 1 || true)"
        if [[ -n "${last_line}" ]]; then
            note_text="${last_line#*| }"
            [[ "${note_text}" == "${last_line}" ]] && note_text="${last_line}"
            echo "${patch_count} patches, latest: ${note_text}"
            return 0
        fi
    fi
    if [[ "${patch_count}" -gt 0 ]]; then
        echo "${patch_count} patches, no notes"
        return 0
    fi
    echo "empty"
}

load_profile() {
    PROJECT=""
    TARGET="standard-tr5310-s"
    PATCH_SET="default"
    JOBS=""
    NO_CLEAN="0"
    POST_SCRIPT=""
    if [[ -f "${profile_file}" ]]; then
        # shellcheck disable=SC1090
        source "${profile_file}"
    fi
}

save_profile() {
    cat > "${profile_file}" <<EOC
# Auto-generated by tools/tr531x/config_build_profile.sh
PROJECT=${PROJECT}
TARGET=${TARGET}
PATCH_SET=${PATCH_SET}
JOBS=${JOBS}
NO_CLEAN=${NO_CLEAN}
POST_SCRIPT=${POST_SCRIPT}
EOC
    echo "[profile] saved: ${profile_file}"
}

choose_project_text() {
    mapfile -t projects < <(list_projects)
    [[ ${#projects[@]} -gt 0 ]] || { echo "No projects found under ${projects_root}" >&2; exit 1; }

    echo "Available projects:"
    local idx=1
    local default_project default_index in_project
    default_project="${PROJECT:-${projects[0]}}"
    default_index=1
    for p in "${projects[@]}"; do
        echo "  ${idx}. ${p}"
        if [[ "${p}" == "${default_project}" ]]; then
            default_index="${idx}"
        fi
        idx=$((idx + 1))
    done

    read -rp "Project number [${default_index}]: " in_project
    if [[ -z "${in_project}" ]]; then
        PROJECT="${default_project}"
    elif [[ "${in_project}" =~ ^[0-9]+$ ]] && (( in_project >= 1 && in_project <= ${#projects[@]} )); then
        PROJECT="${projects[in_project-1]}"
    else
        echo "Invalid project number: ${in_project}" >&2
        exit 1
    fi

    read -rp "Target [${TARGET}]: " in_target
    TARGET="${in_target:-${TARGET}}"

    echo "Available patch-sets:"
    mapfile -t patch_sets < <(list_patch_sets)
    if [[ ${#patch_sets[@]} -eq 0 ]]; then
        echo "  (none)"
    else
        for s in "${patch_sets[@]}"; do
            echo "  - ${s}: $(patch_set_note "${s}")"
        done
    fi
    read -rp "Patch set [${PATCH_SET}]: " in_patch
    PATCH_SET="${in_patch:-${PATCH_SET}}"

    read -rp "Jobs (empty=SDK default) [${JOBS}]: " in_jobs
    JOBS="${in_jobs:-${JOBS}}"

    read -rp "Use --no-clean? (0/1) [${NO_CLEAN}]: " in_no_clean
    NO_CLEAN="${in_no_clean:-${NO_CLEAN}}"

    read -rp "Post script [${POST_SCRIPT}]: " in_post
    POST_SCRIPT="${in_post:-${POST_SCRIPT}}"
}

load_profile
choose_project_text
save_profile
